# Generated by Django 4.2.5 on 2024-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_course_options_lesson_is_free'),
        ('authapp', '0003_studentuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='free_lessons',
            field=models.ManyToManyField(blank=True, related_name='students', to='mainapp.lesson', verbose_name='Бесплатные уроки'),
        ),
    ]
