# Generated by Django 4.2.5 on 2023-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Откроется в'),
        ),
    ]
