# Generated by Django 4.2.5 on 2023-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_homework',
            field=models.TextField(blank=True, verbose_name='Описание домашнего задания к уроку'),
        ),
    ]
