# Generated by Django 4.2.5 on 2023-12-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.CharField(blank=True, default='a', max_length=200, verbose_name='Видео в записи'),
            preserve_default=False,
        ),
    ]
