# Generated by Django 4.2.5 on 2024-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_course_options_lesson_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступ к курсу в днях'),
        ),
        migrations.AddField(
            model_name='course',
            name='group_is_full',
            field=models.BooleanField(default=False, verbose_name='Поток набран'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_starts_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта уроков'),
        ),
    ]
