# Generated by Django 4.2.5 on 2024-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_lesson_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('Онлайн-урок', 'Online Lesson'), ('Видеоурок', 'Video Lesson')], max_length=13, verbose_name='Тип урока'),
        ),
    ]
