# Generated by Django 4.2.5 on 2024-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_free',
            field=models.ImageField(blank=True, null=True, upload_to='free_lessons_img/', verbose_name='Изображение к карточке бесплатного урока'),
        ),
    ]
