# Generated by Django 4.2.5 on 2024-03-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_lesson_image_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='access_days',
        ),
    ]
