name: CI/CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run command on remote server

        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd Petroglif_school;
            docker compose exec web python manage.py savedump;
            docker compose -f docker-compose.prod.yml down;
            git checkout .;
            git pull;
            docker compose -f docker-compose.prod.yml up --build -d;
  clean:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clean docker garbage

        uses: appleboy/ssh-action@v1.0.0

        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            script: docker system prune -af;

